version: '3.8'

services:
  backend:
    build: .
    container_name: backend-fastapi
    ports:
      - "8000:8000"
    environment:
      - MONGO_URL=mongodb://mongo:27017/myletterdb
      - JWT_SECRET=supersecretkey123
      - ALGORITHM=HS256
      - OPENAI_API_KEY=${OPENAI_API_KEY}
    volumes:
      - .:/app
    depends_on:
      - mongo
    restart: unless-stopped

  mongo:
    image: mongo:latest
    container_name: mongodb
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=adminpass
    volumes:
      - mongo_data:/data/db
    restart: unless-stopped

  mongo-express:
    image: mongo-express
    container_name: mongo-express
    ports:
      - "8081:8081"
    environment:
      - ME_CONFIG_MONGODB_SERVER=mongo
      - ME_CONFIG_MONGODB_ADMINUSERNAME=admin
      - ME_CONFIG_MONGODB_ADMINPASSWORD=adminpass
    depends_on:
      - mongo
    restart: unless-stopped

volumes:
  mongo_data: